services:
  - type: web
    name: sample-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 1
